"""empty message

Revision ID: 2a1bc83c30f5
Revises: 8aaf1f8bfb9a
Create Date: 2021-07-07 14:07:37.673084

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a1bc83c30f5'
down_revision = '8aaf1f8bfb9a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_detail', 'code')
    op.drop_column('next_of_kin', 'img')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('next_of_kin', sa.Column('img', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('bank_detail', sa.Column('code', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
