"""empty message

Revision ID: 470f92cff2f1
Revises: a7b4b05dc669
Create Date: 2021-06-06 12:59:51.581615

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '470f92cff2f1'
down_revision = 'a7b4b05dc669'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_attendance', 'type',
               existing_type=mysql.ENUM('Clock In', 'Clock Out'),
               nullable=False)
    op.add_column('user_deduction', sa.Column('period_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'user_deduction', 'period', ['period_id'], ['id'], ondelete='cascade')
    op.add_column('user_earning', sa.Column('period_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'user_earning', 'period', ['period_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_earning', type_='foreignkey')
    op.drop_column('user_earning', 'period_id')
    op.drop_constraint(None, 'user_deduction', type_='foreignkey')
    op.drop_column('user_deduction', 'period_id')
    op.alter_column('user_attendance', 'type',
               existing_type=mysql.ENUM('Clock In', 'Clock Out'),
               nullable=True)
    # ### end Alembic commands ###
