"""empty message

Revision ID: 52d703767da6
Revises: 88d92e604b53
Create Date: 2021-05-25 22:26:07.595109

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '52d703767da6'
down_revision = '88d92e604b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET FOREIGN_KEY_CHECKS=0")
    op.drop_index('period_id', table_name='attendance')
    op.execute("SET FOREIGN_KEY_CHECKS=1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('period_id', 'attendance', ['period_id'], unique=True)
    # ### end Alembic commands ###
