"""empty message

Revision ID: 60e51a444165
Revises: cbee2cba844b
Create Date: 2021-05-16 16:35:10.081103

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60e51a444165'
down_revision = 'cbee2cba844b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'proof')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('proof', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
