"""first_migration

Revision ID: 6e441ced52dd
Revises: 
Create Date: 2021-07-16 16:17:28.216315

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6e441ced52dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER'), nullable=True),
    sa.Column('superuser', sa.Boolean(), nullable=True),
    sa.Column('hrm_support', sa.Boolean(), nullable=True),
    sa.Column('payroll_support', sa.Boolean(), nullable=True),
    sa.Column('last_logged_in', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('business',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('support_email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('logo', sa.String(length=100), nullable=True),
    sa.Column('btype', sa.Enum('Nonprofit Organization', 'Sole Proprietorship', 'Partnership', 'Corporation', 'Limited Liability Company'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('bank',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('business_account',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.Enum('Bank Account', 'Mobile Money'), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('department',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbr', sa.String(length=100), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('memo',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('period',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('make_payment', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('personnel_group',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('FullTime', 'PartTime', 'Intern', 'Contract'), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('queue',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('setting',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('notify_payment_by_sms', sa.Boolean(), nullable=True),
    sa.Column('notify_payment_by_email', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('period_id', sa.String(length=100), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('deduction_group',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('personnel_group_id', sa.String(length=100), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('per_day', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['personnel_group_id'], ['personnel_group.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('earning_group',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('personnel_group_id', sa.String(length=100), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('per_day', sa.Boolean(), nullable=True),
    sa.Column('allowance', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['personnel_group_id'], ['personnel_group.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('social_security_rate',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('period_id', sa.String(length=100), nullable=False),
    sa.Column('emp_rate', sa.Float(), nullable=False),
    sa.Column('emper_rate', sa.Float(), nullable=False),
    sa.Column('tier1', sa.Float(), nullable=False),
    sa.Column('tier2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tax',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('period_id', sa.String(length=100), nullable=False),
    sa.Column('personnel_group_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('automate', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['personnel_group_id'], ['personnel_group.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_meta',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('personnel_group_id', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Enum('MRS', 'MISS', 'MR', 'MS'), nullable=True),
    sa.Column('marital_status', sa.Enum('Married', 'Divorced', 'Widowed', 'Single'), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female'), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('retired', sa.Boolean(), nullable=True),
    sa.Column('resigned', sa.Boolean(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('addr', sa.Text(), nullable=True),
    sa.Column('ssn', sa.String(length=50), nullable=True),
    sa.Column('tin', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['personnel_group_id'], ['personnel_group.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('working_day',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('period_id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('personnel_group_id', sa.String(length=100), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['personnel_group_id'], ['personnel_group.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('bank_detail',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('bank_id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('user_meta_id', sa.String(length=100), nullable=False),
    sa.Column('no', sa.String(length=50), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_meta_id'], ['user_meta.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('daily_rate',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('period_id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('user_meta_id', sa.String(length=100), nullable=False),
    sa.Column('main_amount', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('emergency_amount', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_meta_id'], ['user_meta.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('next_of_kin',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('user_meta_id', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_meta_id'], ['user_meta.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_attendance',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('user_meta_id', sa.String(length=100), nullable=False),
    sa.Column('attendance_id', sa.String(length=100), nullable=False),
    sa.Column('attype', sa.Enum('Absent', 'Excused Duty', 'Present'), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('Clock In', 'Clock Out'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_meta_id'], ['user_meta.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_deduction',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('user_meta_id', sa.String(length=100), nullable=False),
    sa.Column('deduction_group_id', sa.String(length=100), nullable=False),
    sa.Column('period_id', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['deduction_group_id'], ['deduction_group.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_meta_id'], ['user_meta.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_doc',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('user_meta_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('doc', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_meta_id'], ['user_meta.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_earning',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('user_meta_id', sa.String(length=100), nullable=False),
    sa.Column('earning_group_id', sa.String(length=100), nullable=False),
    sa.Column('period_id', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['earning_group_id'], ['earning_group.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_meta_id'], ['user_meta.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_leave',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('user_meta_id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('without_pay', sa.Boolean(), nullable=True),
    sa.Column('ltype', sa.String(length=50), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_meta_id'], ['user_meta.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_leave')
    op.drop_table('user_earning')
    op.drop_table('user_doc')
    op.drop_table('user_deduction')
    op.drop_table('user_attendance')
    op.drop_table('next_of_kin')
    op.drop_table('daily_rate')
    op.drop_table('bank_detail')
    op.drop_table('working_day')
    op.drop_table('user_meta')
    op.drop_table('tax')
    op.drop_table('social_security_rate')
    op.drop_table('earning_group')
    op.drop_table('deduction_group')
    op.drop_table('attendance')
    op.drop_table('setting')
    op.drop_table('queue')
    op.drop_table('personnel_group')
    op.drop_table('period')
    op.drop_table('memo')
    op.drop_table('department')
    op.drop_table('business_account')
    op.drop_table('bank')
    op.drop_table('business')
    op.drop_table('user')
    # ### end Alembic commands ###
