"""empty message

Revision ID: 768d04074521
Revises: fe88395f6f11
Create Date: 2021-06-23 19:05:30.456319

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '768d04074521'
down_revision = 'fe88395f6f11'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_meta', 'gender',
               existing_type=mysql.ENUM('Male', 'Female'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_meta', 'gender',
               existing_type=mysql.ENUM('Male', 'Female'),
               nullable=False)
    # ### end Alembic commands ###
