"""empty message

Revision ID: 85156d913fbc
Revises: 7793dd9b2a69
Create Date: 2021-05-17 00:10:27.261989

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85156d913fbc'
down_revision = '7793dd9b2a69'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('day', sa.Date(), nullable=False))
    op.alter_column('business', 'logo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business', 'logo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('attendance', 'day')
    # ### end Alembic commands ###
