"""empty message

Revision ID: 88d92e604b53
Revises: 82d55b689f99
Create Date: 2021-05-24 22:42:50.250982

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88d92e604b53'
down_revision = '82d55b689f99'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_account', 'name')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_account', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
