"""empty message

Revision ID: 8aaf1f8bfb9a
Revises: fe6e61b59d27
Create Date: 2021-07-07 09:01:29.383239

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8aaf1f8bfb9a'
down_revision = 'fe6e61b59d27'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_attendance', sa.Column('time', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_attendance', 'time')
    # ### end Alembic commands ###
