"""empty message

Revision ID: 8c6b5162b809
Revises: 470f92cff2f1
Create Date: 2021-06-06 13:58:06.793543

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c6b5162b809'
down_revision = '470f92cff2f1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deduction_group', 'amount')
    op.drop_column('earning_group', 'amount')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earning_group', sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('deduction_group', sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###
