"""empty message

Revision ID: 8ecf62eca598
Revises: 8c6b5162b809
Create Date: 2021-06-23 18:57:27.412281

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ecf62eca598'
down_revision = '8c6b5162b809'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_meta', 'department_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user_meta', 'personnel_group_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_meta', 'personnel_group_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_meta', 'department_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
