"""empty message

Revision ID: 977751c9957f
Revises: f988e5d00fd6
Create Date: 2021-05-16 19:15:33.927996

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '977751c9957f'
down_revision = 'f988e5d00fd6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'attendance', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('bank', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'bank', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('bank_detail', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'bank_detail', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('daily_rate', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'daily_rate', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('deduction_group', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'deduction_group', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('department', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'department', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('earning_group', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'earning_group', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('memo', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'memo', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('next_of_kin', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'next_of_kin', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('period', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'period', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('personnel_group', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'personnel_group', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('queue', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'queue', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('social_security_rate', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'social_security_rate', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('tax', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'tax', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('user_attendance', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'user_attendance', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('user_deduction', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'user_deduction', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('user_doc', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'user_doc', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('user_earning', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'user_earning', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('user_leave', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'user_leave', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('user_meta', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'user_meta', 'business', ['business_id'], ['id'], ondelete='cascade')
    op.add_column('working_day', sa.Column('business_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'working_day', 'business', ['business_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'working_day', type_='foreignkey')
    op.drop_column('working_day', 'business_id')
    op.drop_constraint(None, 'user_meta', type_='foreignkey')
    op.drop_column('user_meta', 'business_id')
    op.drop_constraint(None, 'user_leave', type_='foreignkey')
    op.drop_column('user_leave', 'business_id')
    op.drop_constraint(None, 'user_earning', type_='foreignkey')
    op.drop_column('user_earning', 'business_id')
    op.drop_constraint(None, 'user_doc', type_='foreignkey')
    op.drop_column('user_doc', 'business_id')
    op.drop_constraint(None, 'user_deduction', type_='foreignkey')
    op.drop_column('user_deduction', 'business_id')
    op.drop_constraint(None, 'user_attendance', type_='foreignkey')
    op.drop_column('user_attendance', 'business_id')
    op.drop_constraint(None, 'tax', type_='foreignkey')
    op.drop_column('tax', 'business_id')
    op.drop_constraint(None, 'social_security_rate', type_='foreignkey')
    op.drop_column('social_security_rate', 'business_id')
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.drop_column('queue', 'business_id')
    op.drop_constraint(None, 'personnel_group', type_='foreignkey')
    op.drop_column('personnel_group', 'business_id')
    op.drop_constraint(None, 'period', type_='foreignkey')
    op.drop_column('period', 'business_id')
    op.drop_constraint(None, 'next_of_kin', type_='foreignkey')
    op.drop_column('next_of_kin', 'business_id')
    op.drop_constraint(None, 'memo', type_='foreignkey')
    op.drop_column('memo', 'business_id')
    op.drop_constraint(None, 'earning_group', type_='foreignkey')
    op.drop_column('earning_group', 'business_id')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'business_id')
    op.drop_constraint(None, 'deduction_group', type_='foreignkey')
    op.drop_column('deduction_group', 'business_id')
    op.drop_constraint(None, 'daily_rate', type_='foreignkey')
    op.drop_column('daily_rate', 'business_id')
    op.drop_constraint(None, 'bank_detail', type_='foreignkey')
    op.drop_column('bank_detail', 'business_id')
    op.drop_constraint(None, 'bank', type_='foreignkey')
    op.drop_column('bank', 'business_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'business_id')
    # ### end Alembic commands ###
