"""empty message

Revision ID: f0249b5cd883
Revises: 768d04074521
Create Date: 2021-07-07 08:52:56.653640

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0249b5cd883'
down_revision = '768d04074521'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_attendance', 'attype')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_attendance', sa.Column('attype', mysql.ENUM('Absent', 'Excused Duty', 'Present'), nullable=False))
    # ### end Alembic commands ###
