"""empty message

Revision ID: fb25a18bbba0
Revises: 85156d913fbc
Create Date: 2021-05-17 01:02:25.406152

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fb25a18bbba0'
down_revision = '85156d913fbc'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('allow_tax_paye', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'allow_tax_paye')
    # ### end Alembic commands ###
