"""empty message

Revision ID: fe6e61b59d27
Revises: 168017ba4886
Create Date: 2021-07-07 09:01:09.877831

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe6e61b59d27'
down_revision = '168017ba4886'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_attendance', 'time')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_attendance', sa.Column('time', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
