"""empty message

Revision ID: fe88395f6f11
Revises: 8ecf62eca598
Create Date: 2021-06-23 19:04:33.477431

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe88395f6f11'
down_revision = '8ecf62eca598'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_meta', 'marital_status',
               existing_type=mysql.ENUM('Married', 'Divorced', 'Widowed', 'Single'),
               nullable=True)
    op.alter_column('user_meta', 'religion',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user_meta', 'ssn',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user_meta', 'tin',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_meta', 'tin',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user_meta', 'ssn',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user_meta', 'religion',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user_meta', 'marital_status',
               existing_type=mysql.ENUM('Married', 'Divorced', 'Widowed', 'Single'),
               nullable=False)
    # ### end Alembic commands ###
