from .attendance import namespace as attendance
from .bank import namespace as bank
from .bank_detail import namespace as bank_detail
from .business import namespace as business
from .business import namespace as business
from .business_account import namespace as business_account
from .daily_rate import namespace as daily_rate
from .deduction_group import namespace as deduction_group
from .department import namespace as department
from .earning_group import namespace as earning_group
from .memo import namespace as memo
from .next_of_kin import namespace as next_of_kin
from .period import namespace as period
from .personnel_group import namespace as personnel_group
from .queue import namespace as queue
from .settings import namespace as settings
from .social_security_rate import namespace as social_security_rate
from .tax import namespace as tax
from .upload import namespace as upload
from .user_attendance import namespace as user_attendance
from .user_deduction import namespace as user_deduction
from .user_doc import namespace as user_doc
from .user_earning import namespace as user_earning
from .user_leave import namespace as user_leave
from .user_manager import namespace as user_manager
from .user_manager import namespace as user_manager
from .working_day import namespace as working_day
from .profile import namespace as profile
from .reports import namespace as reports
